### ISSUE TITLE
无法打开源文件 "unicode/msvclib.h" 

### ISSUE THREAD

**Issue by huoxiangdong** [Gaazar/RLL#2]
<img width="272" alt="image" src="https://github.com/Gaazar/RLL/assets/18095882/0b4245ff-60ef-44da-9eef-ef1a3295744f">
唯独缺少这个msvclib.h文件，是依赖装错了吗?
是否可以将依赖包含在项目里, 依赖搞的比较头疼

**Comment by huoxiangdong** [comment]
icu, freetype, harfbuzz 主要是这三个库吗? 包含到项目里是不是比较好点呢?

**Comment by Gaazar** [comment]
已经把这个文件移除了。
🤯这个项目时间有点久远，有些东西我自己都不太记得了。大概就是只有这三个库。

**Comment by huoxiangdong** [comment]
好的
